### ISSUE TITLE
describe the repo

### ISSUE THREAD

**Issue by harry-wood** [neontribe/gbptm-ui-deprecated#32]
Can you add a README.txt here?

Key questions:
Is this the source code powering http://greatbritishpublictoiletmap.rca.ac.uk ?
Why is it named 'deprecated'?

**Comment by marxian** [comment]
I should... Better still I should retire this repo which is a left-over from some refactoring.

The code currently running http://greatbritishpublictoiletmap.rca.ac.uk is here: https://github.com/neontribe/gbptm

**Comment by marxian** [comment]
README added...

**Comment by harry-wood** [comment]
ah I see. I read the top description of 'gbptm' and thought that was just the API.

**Comment by marxian** [comment]
I fixed that too ;-)

On 19 November 2015 at 14:50, Harry Wood <notifications@github.com> wrote:

> ah I see. I read the top description of 'gbptm' and thought that was just
> the API.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neontribe/gbptm-ui-deprecated/issues/32#issuecomment-158078614>
> .
>



-- 

@rupertredington | 07780 995152 | http://www.neontribe.co.uk

Terse? I loosely adhere to http://five.sentenc.es

The views expressed in this email have almost certainly been lifted from
elsewhere.
